[package]
name = "sod_rsa2048_v15_sha256_ec1024"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
hash = { path = "../../../lib/core/hash" }
commit = { path = "../../../lib/core/commit" }
rsa = { path = "../../../lib/core/rsa" }
sod = { path = "../../../lib/emrtd/sod" }
testdata = { path = "../../../lib/testdata" }
