[package]
name = "sod_ecdsa_p256_sha256_ec512"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
commit = { path = "../../../lib/core/commit" }
sig = { path = "../../../lib/core/sig" }
sod = { path = "../../../lib/emrtd/sod" }
testdata = { path = "../../../lib/testdata" }
