[package]
name = "nullifier_document_number"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
commit = { path = "../../../lib/core/commit" }
nullifier = { path = "../../../lib/claims/nullifier" }
predicate = { path = "../../../lib/claims/predicate" }
