[package]
name = "registration_mrz_td3_ecdsa_p256_sha256_ec512_inclusion"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.2.0-aztecnr-rc.2", directory = "barretenberg/noir/bb_proof_verification" }
