[package]
name = "dg_extract_sha256_ec512"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
commit = { path = "../../../lib/core/commit" }
dg_extract = { path = "../../../lib/emrtd/dg_extract" }
hash = { path = "../../../lib/core/hash" }
testdata = { path = "../../../lib/testdata" }
