[package]
name = "mrz_opening"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
attributes = { path = "../../lib/attributes" }
commit = { path = "../../lib/commit" }
hash = { path = "../../lib/hash" }
mrz = { path = "../../lib/mrz" }
normalize = { path = "../../lib/normalize" }
