[package]
name = "mrz_opening"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
attributes = { path = "../../lib/emrtd/attributes" }
commit = { path = "../../lib/core/commit" }
hash = { path = "../../lib/core/hash" }
mrz = { path = "../../lib/emrtd/mrz" }
normalize = { path = "../../lib/core/normalize" }
