#!/usr/bin/env python3
"""Regenerates the Poseidon2 constants from the pinned Barretenberg source.

The Noir circuits hash with Poseidon2 as Barretenberg implements it, exposed
through std::hash::poseidon2_permutation. A circom port that used any other
constants would compute a different value and prove nothing about a document
the Noir side committed. So the constants are taken from the same revision
the toolchain pins rather than transcribed from a paper, and this script is
how they are taken.

    python3 tools/constants.py ~/nargo/github.com/AztecProtocol/aztec-packages/<tag>

Agreement is still checked against vectors the Noir side produced; matching
constants are a reason to expect agreement, not evidence of it.
"""

import re
import sys
from pathlib import Path

HEADER = """// Generated by tools/constants.py from the Poseidon2 parameters of the
// pinned Barretenberg revision. Do not edit: regenerate so these stay the
// constants the Noir side actually uses.
//
// BN254, width 4, alpha 5, 8 external rounds and 56 internal.
pragma circom 2.1.6;
"""


def main():
    if len(sys.argv) < 2:
        print(__doc__)

        return 2

    params = (
        Path(sys.argv[1])
        / "barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_params.hpp"
    )

    if not params.exists():
        print(f"no Poseidon2 parameters at {params}", file=sys.stderr)

        return 2

    text = params.read_text()

    start = text.index("round_constants{")

    block = text[start : text.index("};", start)]

    hexes = re.findall(r"0x([0-9a-fA-F]{64})", block)

    if len(hexes) != 256:
        print(f"expected 256 round constants, found {len(hexes)}", file=sys.stderr)

        return 1

    diagonal_start = text.index("internal_matrix_diagonal_minus_one = {")

    diagonal = re.findall(
        r"0x([0-9a-fA-F]{64})", text[diagonal_start : text.index("};", diagonal_start)]
    )

    if len(diagonal) != 4:
        print(f"expected 4 diagonal entries, found {len(diagonal)}", file=sys.stderr)

        return 1

    lines = [HEADER, "function POSEIDON2_ROUND_CONSTANTS() {", "    return ["]

    for index in range(64):
        row = ", ".join(f"0x{h}" for h in hexes[index * 4 : index * 4 + 4])

        lines.append(f"        [{row}]" + ("," if index < 63 else ""))

    lines += ["    ];", "}", ""]

    lines += [
        "// The internal layer multiplies by the identity plus a diagonal, so only",
        "// D_i - 1 is stored: out[i] = (D_i - 1) * x[i] + sum(x).",
        "function POSEIDON2_INTERNAL_DIAGONAL_MINUS_ONE() {",
        "    return [",
    ]

    for index, value in enumerate(diagonal):
        lines.append(f"        0x{value}" + ("," if index < 3 else ""))

    lines += ["    ];", "}", ""]

    destination = Path(__file__).resolve().parent.parent / "poseidon2/constants.circom"

    destination.write_text("\n".join(lines))

    print(f"wrote {destination}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
