[package]
name = "anchor_dsc_inclusion"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
anchor = { path = "../../../lib/trust/anchor" }
commit = { path = "../../../lib/core/commit" }
