//! Writes the verification key hashes the registration circuit pins.
//!
//! The hash of a verification key depends on the compiled circuit alone, not
//! on any document, so these are constants of a toolchain revision. They are
//! generated and committed like the layout manifest: when a circuit changes,
//! regenerating makes the change visible in a diff, and a stale file shows up
//! as a registration proof that fails to verify.

use std::fmt::Write as _;
use std::path::Path;

use crate::ec;
use crate::scratch::Scratch;

/// The inner circuits the first registration instantiation aggregates, and
/// the constant each hash is emitted under.
const INNER: [(&str, &str); 4] = [
    ("SOD", "sod_ecdsa_p256_sha256_ec512"),
    ("DG_EXTRACT", "dg_extract_sha256_ec512"),
    ("ATTRIBUTES", "attributes_mrz_td3_sha256"),
    ("ANCHOR", "anchor_dsc_inclusion"),
];

const DESTINATION: &str = "bin/registration/mrz_td3_ecdsa_p256_sha256_ec512_inclusion/src/keys.nr";

const HEADER: &str = "\
//! Generated by fixtures/generator with the keys subcommand. Do not edit.
//!
//! The hash of each inner circuit's verification key. Compiling these in is
//! what makes this circuit's identity fix the exact variants it aggregates,
//! the way an off chain verifier's accepted key list does.

";

pub fn write(circuits_root: &Path) {
    let work = Scratch::new("keys");

    let mut body = String::from(HEADER);

    for (name, package) in INNER {
        ec::run(
            "nargo",
            &[
                "compile",
                "--package",
                package,
                "--program-dir",
                circuits_root.to_str().unwrap(),
            ],
            None,
        );

        let bytecode = circuits_root.join(format!("target/{package}.json"));

        let directory = work.join(name);

        std::fs::create_dir_all(&directory).expect("cannot create a key scratch directory");

        ec::run(
            "bb",
            &[
                "write_vk",
                "-b",
                bytecode.to_str().unwrap(),
                "-o",
                directory.to_str().unwrap(),
            ],
            None,
        );

        let hash = std::fs::read(directory.join("vk_hash")).expect("bb wrote no key hash");

        assert_eq!(hash.len(), 32, "a key hash is one field element");

        let mut hex = String::from("0x");

        for byte in &hash {
            write!(hex, "{byte:02x}").unwrap();
        }

        writeln!(body, "pub global {name}: Field = {hex};\n").unwrap();
    }

    let destination = circuits_root.join(DESTINATION);

    std::fs::write(&destination, body.trim_end().to_string() + "\n")
        .expect("cannot write the key hashes");

    println!("wrote {}", destination.display());
}
