//! Writes the verification key hashes the recursive circuits pin.
//!
//! The hash of a verification key depends on the compiled circuit alone, not
//! on any document, so these are constants of a toolchain revision. They are
//! generated and committed like the layout manifest: when a circuit changes,
//! regenerating makes the change visible in a diff, and a stale file shows up
//! as a recursive proof that fails to verify.

use std::fmt::Write as _;
use std::path::Path;

use crate::ec;
use crate::scratch::Scratch;

/// Each recursive circuit and the inner circuits it pins, in the order the
/// constants are emitted into its keys.nr.
const TARGETS: [(&str, &[(&str, &str)]); 3] = [
    (
        "bin/registration/mrz_td3_ecdsa_p256_sha256_ec512_inclusion/src/keys.nr",
        &[
            ("SOD", "sod_ecdsa_p256_sha256_ec512"),
            ("DG_EXTRACT", "dg_extract_sha256_ec512"),
            ("ATTRIBUTES", "attributes_mrz_td3_sha256"),
            ("ANCHOR", "anchor_dsc_inclusion"),
        ],
    ),
    (
        "bin/registration/mrz_td3_ecdsa_p256_sha256_ec512_csca_chain/src/keys.nr",
        &[
            ("SOD", "sod_ecdsa_p256_sha256_ec512"),
            ("DG_EXTRACT", "dg_extract_sha256_ec512"),
            ("ATTRIBUTES", "attributes_mrz_td3_sha256"),
            ("ANCHOR", "anchor_csca_chain_rsa2048_sha256_tbs512"),
        ],
    ),
    (
        "bin/session/compare_member/src/keys.nr",
        &[
            ("COMPARE", "predicate_compare"),
            ("MEMBER", "predicate_member"),
        ],
    ),
];

const HEADER: &str = "\
//! Generated by fixtures/generator with the keys subcommand. Do not edit.
//!
//! The hash of each inner circuit's verification key. Compiling these in is
//! what makes this circuit's identity fix the exact variants it aggregates,
//! the way an off chain verifier's accepted key list does.

";

/// Writes the key hash files.
pub fn write(circuits_root: &Path) {
    emit(circuits_root, Mode::Write);
}

/// Recomputes them and reports whether the committed ones still match.
///
/// A recursive circuit compiles whatever hashes it was given, so a stale
/// file is not a build error: it is a proof that fails to verify, later and
/// somewhere else. This is the check that turns that into a failure here.
pub fn check(circuits_root: &Path) -> bool {
    emit(circuits_root, Mode::Check)
}

#[derive(Clone, Copy, PartialEq)]
enum Mode {
    Write,
    Check,
}

fn emit(circuits_root: &Path, mode: Mode) -> bool {
    let work = Scratch::new("keys");

    let mut current = true;

    for (destination, inner) in TARGETS {
        let mut body = String::from(HEADER);

        for (name, package) in inner {
            ec::run(
                "nargo",
                &[
                    "compile",
                    "--package",
                    package,
                    "--program-dir",
                    circuits_root.to_str().unwrap(),
                ],
                None,
            );

            let bytecode = circuits_root.join(format!("target/{package}.json"));

            let directory = work.join(&format!("{name}_{package}"));

            std::fs::create_dir_all(&directory).expect("cannot create a key scratch directory");

            ec::run(
                "bb",
                &[
                    "write_vk",
                    "-b",
                    bytecode.to_str().unwrap(),
                    "-o",
                    directory.to_str().unwrap(),
                ],
                None,
            );

            let hash = std::fs::read(directory.join("vk_hash")).expect("bb wrote no key hash");

            assert_eq!(hash.len(), 32, "a key hash is one field element");

            let mut hex = String::from("0x");

            for byte in &hash {
                write!(hex, "{byte:02x}").unwrap();
            }

            writeln!(body, "pub global {name}: Field = {hex};\n").unwrap();
        }

        let path = circuits_root.join(destination);

        let wanted = body.trim_end().to_string() + "\n";

        if mode == Mode::Check {
            let committed = std::fs::read_to_string(&path).unwrap_or_default();

            if committed == wanted {
                println!("current  {destination}");
            } else {
                println!("STALE    {destination}");

                current = false;
            }

            continue;
        }

        std::fs::write(&path, wanted).expect("cannot write the key hashes");

        println!("wrote {}", path.display());
    }

    current
}
