//! Writes an input template beside every circuit.
//!
//! A circuit's witness file is not committed, because a real one holds a
//! holder's document. What is committed is a template with the same field
//! names and a placeholder in every value, so someone who clones this
//! repository can see exactly what a circuit expects and where their own
//! material goes, without a fixture standing in for it.
//!
//! Generated from the compiled ABI rather than written by hand, so a
//! circuit whose inputs change cannot leave a template describing the old
//! ones.

use std::fmt::Write as _;
use std::path::Path;

use crate::manifest;

const HEADER: &str = "\
# Generated by fixtures/generator with the templates subcommand. Do not edit.
#
# Copy this to Prover.toml and replace every placeholder with your own
# material. Nothing here is a working value: a witness holds one holder's
# document, so no real one is committed anywhere in this repository.
#
# Where a value comes from is written beside it. The witness tools under
# tools/ derive the ones that are hashes of something else, so that they are
# computed by the same library the circuit checks them against.
";

/// What a reader needs to know about a name, keyed by the prefix that
/// identifies it. Longest match wins, so a specific name beats a general one.
const GUIDANCE: &[(&str, &str)] = &[
    ("domain", "your application, a non zero value distinct from every other application"),
    ("context", "a fresh non zero value the verifier issued for this exchange"),
    ("dsc_salt", "a fresh random value, or zero for the public registry convention; the anchor proof must use the same one"),
    ("salt", "the same value the sod proof used as dsc_salt"),
    ("length", "the field's length in bytes before packing"),
    ("data", "the packed field, from the opening tool"),
    ("field_id", "which field this statement is about; see the profile"),
    ("minimum", "the lower bound you are asking the holder to prove"),
    ("maximum", "the upper bound you are asking the holder to prove"),
    ("revealed_length", "the length of the field you are disclosing"),
    ("revealed", "the packed field you are disclosing, from the opening tool"),
    ("index", "which leaf of the published tree is yours"),
    ("public_key_offset", "byte offset of the subject public key inside tbs"),
    ("not_before_offset", "byte offset of the notBefore time inside tbs"),
    ("not_after_offset", "byte offset of the notAfter time inside tbs"),
    ("econtent_len", "the true length of the Security Object, in bytes"),
    ("econtent", "the Security Object read from the chip, zero padded"),
    ("signed_attrs_len", "the true length of the signed attributes"),
    ("signed_attrs", "the CMS signed attributes, zero padded"),
    ("digest_offset", "byte offset of the messageDigest value inside signed_attrs"),
    ("oid_offset", "byte offset of the digest algorithm identifier inside econtent"),
    ("dg_offset", "byte offset of the data group entry inside econtent"),
    ("dg_number", "which data group this proof is about, 1 to 16"),
    ("dg1_len", "the true length of DG1, in bytes"),
    ("dg1", "DG1 read from the chip, zero padded"),
    ("pubkey_x", "x coordinate of the signer public key, 32 bytes"),
    ("pubkey_y", "y coordinate of the signer public key, 32 bytes"),
    ("signature_r", "r of the signature over the signed attributes, 32 bytes"),
    ("signature_s", "s of that signature, normalized to at most n/2"),
    ("modulus_limbs", "the RSA modulus as 120 bit limbs"),
    ("redc_limbs", "the Barrett parameter for that modulus"),
    ("signature_limbs", "the RSA signature as 120 bit limbs"),
    ("authority_modulus", "the country signing key modulus as limbs"),
    ("authority_redc", "the Barrett parameter for the authority modulus"),
    ("authority_signature", "the authority signature over tbs, as limbs"),
    ("tbs_len", "the true length of the certificate body"),
    ("tbs", "the signer certificate body, zero padded"),
    ("current_yyyymmdd", "the date this proof is made, as YYYYMMDD"),
    ("session_salt", "a fresh random non zero value; keep it to open this commitment later"),
];

/// Names whose placeholder should say to run a tool rather than invent a value.
const FROM_TOOL: &[(&str, &str)] = &[
    (
        "key",
        "the verification key of that inner circuit, as 115 field elements: bb write_vk",
    ),
    (
        "proof",
        "that inner circuit's proof, as 500 field elements: bb prove",
    ),
    ("econtent_binding", "return[0] of the sod proof"),
    ("dg_binding", "return[0] of the dg_extract proof"),
    ("commitment", "return[0] of the attributes proof"),
    ("secret_binding", "return[2] of the sod proof"),
    ("secret", "tools/document_secret"),
    ("entropy", "tools/mrz_opening"),
    (
        "siblings",
        "tools/merkle_path, or tools/mrz_opening for a field opening",
    ),
    (
        "set_root",
        "tools/merkle_path over tools/set_entry_leaf entries",
    ),
    (
        "registry_root",
        "tools/merkle_path over tools/pubkey_leaf entries",
    ),
    (
        "master_list_root",
        "tools/merkle_path over tools/modulus_leaf entries",
    ),
];

pub fn write(circuits_root: &Path) {
    let mut written = 0;

    for package in manifest::circuit_packages(circuits_root) {
        let bytecode = circuits_root.join(format!("target/{}.json", package.name));

        assert!(
            bytecode.exists(),
            "{} has not been compiled; run nargo compile first",
            package.name
        );

        let mut body = String::from(HEADER);

        for parameter in manifest::parameters(&bytecode) {
            body.push('\n');

            if let Some(note) = note(&parameter.name) {
                writeln!(body, "# {note}").unwrap();
            }

            writeln!(body, "{} = {}", parameter.name, placeholder(&parameter)).unwrap();
        }

        let destination = circuits_root
            .join(&package.directory)
            .join("Prover.toml.example");

        std::fs::write(&destination, body).expect("cannot write an input template");

        written += 1;
    }

    println!("wrote {written} input templates");
}

fn note(name: &str) -> Option<String> {
    if let Some((_, source)) = FROM_TOOL
        .iter()
        .filter(|(key, _)| name == *key || name.ends_with(&format!("_{key}")))
        .max_by_key(|(key, _)| key.len())
    {
        return Some(format!("from {source}"));
    }

    GUIDANCE
        .iter()
        .filter(|(key, _)| name == *key || name.ends_with(&format!("_{key}")))
        .max_by_key(|(key, _)| key.len())
        .map(|(_, text)| (*text).to_string())
}

/// A placeholder that names what is missing and cannot be mistaken for a
/// value: every element says so, and a witness built from this file fails
/// to parse rather than proving something meaningless.
fn placeholder(parameter: &manifest::Parameter) -> String {
    let scalar = format!("\"<your {}>\"", parameter.name.replace('_', " "));

    match parameter.length {
        None => scalar,
        Some(length) if length <= 4 => {
            let elements = vec![scalar; length];

            format!("[{}]", elements.join(", "))
        }
        Some(length) => format!("[{scalar}, {scalar}, \"...\"]  # {length} elements in total"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_placeholder_says_what_is_missing() {
        let scalar = placeholder(&manifest::Parameter {
            name: "session_salt".to_string(),
            length: None,
        });

        assert_eq!(scalar, "\"<your session salt>\"");

        let short = placeholder(&manifest::Parameter {
            name: "data".to_string(),
            length: Some(4),
        });

        assert_eq!(short.matches("<your data>").count(), 4);

        // A long array is elided rather than repeated five hundred times,
        // and says how many elements it really takes.
        let long = placeholder(&manifest::Parameter {
            name: "proof".to_string(),
            length: Some(500),
        });

        assert!(long.contains("500 elements in total"));
    }

    // A placeholder that could be mistaken for a value would be worse than
    // none, so no template line may parse as a number or a hex literal.
    #[test]
    fn no_placeholder_looks_like_a_value() {
        for name in ["domain", "commitment", "signature_r"] {
            let text = placeholder(&manifest::Parameter {
                name: name.to_string(),
                length: None,
            });

            assert!(text.contains("<your"), "{name} placeholder is not marked");

            assert!(
                text.trim_matches('"').parse::<u128>().is_err(),
                "{name} placeholder parses as a number"
            );
        }
    }

    // The reason a template exists at all: production source and fixture
    // material have to stay apart. Nargo has no dev-dependencies section and
    // no separate test file, so the rule is positional: every reference to
    // the fixtures sits below the first test in its file, and the helpers
    // that read them sit at the bottom under a banner saying so.
    //
    // This is what actually keeps fixtures out of a compiled circuit, since
    // Noir does not compile test items into main. It is checked here rather
    // than by searching the artifact: the executable half of a compiled
    // circuit is gzipped, and the source map beside it holds every source
    // file by design, so searching the artifact answers a different
    // question than the one that matters.
    #[test]
    fn fixtures_are_referenced_only_below_the_tests() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .expect("unexpected generator location");

        let mut checked = 0;

        for directory in ["lib", "bin"] {
            for source in walk(&root.join(directory)) {
                if source.to_string_lossy().contains("testdata") {
                    continue;
                }

                let text = std::fs::read_to_string(&source).expect("cannot read a source file");

                let Some(use_at) = text.find("testdata::") else {
                    continue;
                };

                let first_test = text.find("#[test").unwrap_or(usize::MAX);

                assert!(
                    use_at > first_test,
                    "{} reads the fixtures above its first test",
                    source.display()
                );

                checked += 1;
            }
        }

        assert!(
            checked > 0,
            "no package reads the fixtures, which cannot be right"
        );
    }

    fn walk(directory: &Path) -> Vec<std::path::PathBuf> {
        let mut found = Vec::new();

        let Ok(entries) = std::fs::read_dir(directory) else {
            return found;
        };

        for entry in entries.flatten() {
            let path = entry.path();

            if path.is_dir() {
                found.extend(walk(&path));
            } else if path.extension().is_some_and(|e| e == "nr") {
                found.push(path);
            }
        }

        found
    }

    #[test]
    fn a_name_takes_the_most_specific_note() {
        // Both "salt" and "session_salt" have guidance; the longer key wins.
        let session = note("session_salt").expect("session_salt has a note");

        assert!(session.contains("keep it to open this commitment later"));

        // A tool sourced name says which tool rather than describing itself.
        assert_eq!(
            note("secret").as_deref(),
            Some("from tools/document_secret")
        );
    }
}
