[package]
name = "anchor_csca_chain_rsa2048_sha256_tbs512"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
anchor = { path = "../../../lib/trust/anchor" }
commit = { path = "../../../lib/core/commit" }
testdata = { path = "../../../lib/testdata" }
